# Generated by Django 4.1.1 on 2022-10-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.TextField(max_length=200, verbose_name='Фото')),
                ('category', models.TextField(
                    choices=[('other', 'Разное'), ('products', 'Продукты'), ('technique', 'Техника'),
                             ('sport', 'Спорт'), ('clothes', 'Одежда')], default='other', verbose_name='Категория')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Остаток')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
        ),
    ]
